title: "Fatma Amor - Data Analyst"
description: "Portfolio & Projects"
theme: jekyll-theme-slate

nav:
  - name: "Home"
    link: /
  - name: "My Projects"
    link: /project
  - name: "Contact"
    link: /contact
