title: "Fatma Amor - Data Analyst" 
description: "Portfolio & Projects" theme: jekyll-theme-slate nav: 
- name: "🏠 Home" 
 link: README.md
- name: " Project" 
 link: project.md 
- name: "Contact"
link: contact.md
